const list= [Afghanistan,	 	 
    Albania,	 
    Algeria,	 	 
    Andorra,	 
    Angola,	 
    Anguilla,	 
    'Antigua and Barbuda'	, 
    Argentina	 ,
    Armenia	 ,
    Aruba	 , 
    Austria	 ,
    Azerbaijan,	 
    Bahamas	 ,
    Bahrain	 ,
    Bangladesh,	 
    Barbados	, 
    Belarus	 ,
    Belgium	 ,
    Belize	 ,
    Benin	 ,
    Bermuda	 ,
    Bhutan	 ,
    Bolivia ,	 
    'Bosnia and Herzegovina	', 
    Botswana	 ,
    Brazil	 ,
    'British Virgin Islands'	 ,
    'Brunei Darussalam'	 ,
    Bulgaria	 ,
    "Burkina Faso"	 ,
    Burundi	 ,
    'Cabo Verde',	 
    Cambodia	 ,
    Cameroon	 ,
    Canada	 ,
    Caribbean	, 
    'Cayman Islands	 ',
    'Central African Republic	',	 
    Chad	 ,
    Chile	 ,
    China,
    Colombia,	 
    Comoros	 ,
    Congo,	 
    'Cook Islands	' ,
    "Costa Rica"	 ,
    "Côte d'Ivoire	",
    Croatia	 ,
    Cuba	 ,
    Curaçao	 ,
    Cyprus	 ,
    Czechia	 ,
    "Democratic People's Republic of Korea	 ",
    'Democratic Republic of the Congo	' ,
    Denmark	 ,
    Djibouti	 ,
    Dominica	, 
    'Dominican Republic	 '	 ,
    Ecuador	 ,
    Egypt	 ,
    'El Salvador'	, 
    'Equatorial Guinea	' ,
    Eritrea	 ,
    Estonia	 ,
    Ethiopia,	 
    Europe	 ,
    Fiji	 ,
    Finland	 ,	 
    France	 ,
    'French Polynesia',
    Gabon	 ,
Gambia	 ,
Georgia	 ,
Germany	 ,
Ghana	 ,
Greece	 ,
Greenland,	 
Grenada	 ,
Guatemala,	 
Guinea	 ,
'Guinea-Bissau',	 
Guyana	 ,
Haiti	 ,
Honduras,	 
Hungary	 ,
Iceland	 ,
India	 ,
Indonesia,	 
'Iran'	 ,
Iraq	 ,
Ireland	 ,
Israel	 ,
Italy	 ,
Jamaica	 ,
Japan	 ,
Jordan	 ,
Kazakhstan,	 
Kenya	 ,
'Kingdom of Eswatini'	, 
Kiribati	 ,
Kosovo	 ,
Kuwait	 ,
Kyrgyzstan,	 
"Lao People's Democratic Republic	"  ,
Latvia	 ,
Lebanon	 ,
Lesotho	 ,
Liberia	 ,
Libya	 ,
Liechtenstein,	 
Lithuania	 ,
Luxembourg	 ,
Madagascar	 ,
Malawi	 ,
Malaysia,	 
Maldives,	 
Mali	 ,
Malta	 ,
'Marshall Islands'	, 
Mauritania	 ,
Mauritius	 ,
Melanesia	 ,
Mexico	  ,
'Micronesia',	 	 
Monaco	 ,
Mongolia	, 
Montenegro	 ,
Montserrat	 ,
Morocco	 ,
Mozambique,	 
Myanmar	 ,
Namibia	 ,
Nauru	 ,
Nepal	 ,
Netherlands	, 
'New Caledonia',	 
'New Zealand'	, 
Nicaragua	 ,
Niger	 ,
Nigeria	 ,	 
Norway	 ,
Oman,
Pakistan	 ,
Palau	 ,
Panama	 ,
'Papua New Guinea'	, 
Paraguay	 ,
Peru	 ,
Philippines,	 
Poland	 ,
Polynesia,	 
Portugal,	 
"Puerto Rico"	, 
Qatar	 ,
'Republic of Korea'	 ,
'Republic of Moldova'	, 
'Republic of North Macedonia'	, 
Romania	 ,
'Russian Federation'	 ,
Rwanda	 ,
'Saint Kitts and Nevis	 ',
'Saint Lucia	 ',
'Saint Vincent and the Grenadines'	 ,
Samoa	 ,
'San Marino',	 
'Sao Tome and Principe	 ',
'Saudi Arabia'	 ,
Senegal	 ,
Serbia	 ,
Seychelles,	 
'Sierra Leone',	 
Singapore	 ,
'Sint Maarten' ,
Slovakia,	 
Slovenia	, 
'Solomon Islands'	 ,
Somalia	 ,
'South Africa',	 
'South Sudan	 '	 ,
Spain,	 
"Sri Lanka",	 
'State of Palestine'	, 	 
Sudan	, 
Suriname	, 
Sweden	 ,
Switzerland	 ,
'Syrian Arab Republic	' ,
Tajikistan	 ,
Thailand	, 
Timor-Leste	, 
Togo	, 
Tonga	 ,
'Trinidad and Tobago'	, 
Tunisia	 ,
Turkey	 ,
Turkmenistan	 ,
'Turks and Caicos Islands	' ,
Tuvalu	 ,
Uganda	 ,
Ukraine	 ,
'United Arab Emirates'	 ,
'United Kingdom of Great Britain' ,
Tanzania	 ,
'United States',	 
Uruguay	 ,
Uzbekistan,	 
Vanuatu	 ,
Venezuela	 ,
Vietnam	 	, 
Yemen	  ,
Zambia	 ,
Zimbabwe ,
]

export {list}